### ISSUE TITLE
An Authentication object was not found in the SecurityContext

### ISSUE THREAD

**Issue by ajayyuvraj** [revinate/grpc-spring-security-demo#3]
How do we fix this ?  Issue when adding @PreAuthorize in gRPC Method... For rest it works fine...
Note: : Application is deployed in wildfly
Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@527ca940: org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:379)
at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:223)
at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)

**Comment by ST-DDT** [comment]
See also this issue:

[WARNING: Security bypass in multi threaded environments](https://github.com/revinate/grpc-spring-security-demo/issues/2)
